USE [wayzeShoop]
GO

/****** Object:  Table [dbo].[WorkingDaysWeek]    Script Date: 25/01/2022 12:40:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WorkingDaysWeek](
	[WorkingDayCode] [bigint] IDENTITY(1,1) NOT NULL,
	[NameOfWorkDay] [varchar](50) NULL,
 CONSTRAINT [PK_WorkingDaysWeek] PRIMARY KEY CLUSTERED 
(
	[WorkingDayCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

