USE [master]
GO

/****** Object:  Database [wayzeShoop]    Script Date: 25/05/2022 13:08:00 ******/
CREATE DATABASE [wayzeShoop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'wayzeShoop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\wayzeShoop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'wayzeShoop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\wayzeShoop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [wayzeShoop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [wayzeShoop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [wayzeShoop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [wayzeShoop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [wayzeShoop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [wayzeShoop] SET ARITHABORT OFF 
GO

ALTER DATABASE [wayzeShoop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [wayzeShoop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [wayzeShoop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [wayzeShoop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [wayzeShoop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [wayzeShoop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [wayzeShoop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [wayzeShoop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [wayzeShoop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [wayzeShoop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [wayzeShoop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [wayzeShoop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [wayzeShoop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [wayzeShoop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [wayzeShoop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [wayzeShoop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [wayzeShoop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [wayzeShoop] SET RECOVERY FULL 
GO

ALTER DATABASE [wayzeShoop] SET  MULTI_USER 
GO

ALTER DATABASE [wayzeShoop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [wayzeShoop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [wayzeShoop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [wayzeShoop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [wayzeShoop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [wayzeShoop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [wayzeShoop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [wayzeShoop] SET  READ_WRITE 
GO


