USE [master]
GO
/****** Object:  Database [wayzeShoop]    Script Date: 25/05/2022 12:39:34 ******/
CREATE DATABASE [wayzeShoop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'wayzeShoop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\wayzeShoop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'wayzeShoop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\wayzeShoop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [wayzeShoop] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [wayzeShoop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [wayzeShoop] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [wayzeShoop] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [wayzeShoop] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [wayzeShoop] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [wayzeShoop] SET ARITHABORT OFF 
GO
ALTER DATABASE [wayzeShoop] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [wayzeShoop] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [wayzeShoop] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [wayzeShoop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [wayzeShoop] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [wayzeShoop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [wayzeShoop] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [wayzeShoop] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [wayzeShoop] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [wayzeShoop] SET  DISABLE_BROKER 
GO
ALTER DATABASE [wayzeShoop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [wayzeShoop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [wayzeShoop] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [wayzeShoop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [wayzeShoop] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [wayzeShoop] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [wayzeShoop] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [wayzeShoop] SET RECOVERY FULL 
GO
ALTER DATABASE [wayzeShoop] SET  MULTI_USER 
GO
ALTER DATABASE [wayzeShoop] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [wayzeShoop] SET DB_CHAINING OFF 
GO
ALTER DATABASE [wayzeShoop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [wayzeShoop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [wayzeShoop] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [wayzeShoop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'wayzeShoop', N'ON'
GO
ALTER DATABASE [wayzeShoop] SET QUERY_STORE = OFF
GO
USE [wayzeShoop]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 25/05/2022 12:39:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[CategoryCode] [bigint] IDENTITY(1,1) NOT NULL,
	[NameCategory] [varchar](50) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[CategoryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CategoryForStor]    Script Date: 25/05/2022 12:39:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CategoryForStor](
	[CategoryCodeForStore] [bigint] IDENTITY(1,1) NOT NULL,
	[categoryCode] [bigint] NOT NULL,
	[CodeStor] [bigint] NOT NULL,
 CONSTRAINT [PK_TatKatgory] PRIMARY KEY CLUSTERED 
(
	[CategoryCodeForStore] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FavoriteStoresForTheUser]    Script Date: 25/05/2022 12:39:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FavoriteStoresForTheUser](
	[FavoriteCode] [bigint] IDENTITY(1,1) NOT NULL,
	[CodeStor] [bigint] NOT NULL,
	[UserCode] [bigint] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Locations]    Script Date: 25/05/2022 12:39:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Locations](
	[LocationCode] [bigint] IDENTITY(1,1) NOT NULL,
	[AxisX] [float] NULL,
	[AxisY] [float] NULL,
	[floor] [int] NULL,
 CONSTRAINT [PK_Locations] PRIMARY KEY CLUSTERED 
(
	[LocationCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Stor]    Script Date: 25/05/2022 12:39:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stor](
	[CodeStor] [bigint] IDENTITY(1,1) NOT NULL,
	[PlaceCode] [bigint] NULL,
	[NameStor] [varchar](50) NULL,
	[OpeningHours] [time](7) NULL,
	[ClosingHours] [time](7) NULL,
	[Sale] [bit] NULL,
 CONSTRAINT [PK_Stor] PRIMARY KEY CLUSTERED 
(
	[CodeStor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 25/05/2022 12:39:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserCode] [bigint] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CategoryForStor]  WITH CHECK ADD  CONSTRAINT [FK_CategoryForStor_Category] FOREIGN KEY([categoryCode])
REFERENCES [dbo].[Category] ([CategoryCode])
GO
ALTER TABLE [dbo].[CategoryForStor] CHECK CONSTRAINT [FK_CategoryForStor_Category]
GO
ALTER TABLE [dbo].[CategoryForStor]  WITH CHECK ADD  CONSTRAINT [FK_CategoryForStor_Stor] FOREIGN KEY([CodeStor])
REFERENCES [dbo].[Stor] ([CodeStor])
GO
ALTER TABLE [dbo].[CategoryForStor] CHECK CONSTRAINT [FK_CategoryForStor_Stor]
GO
ALTER TABLE [dbo].[FavoriteStoresForTheUser]  WITH CHECK ADD  CONSTRAINT [FK_FavoriteParkingForTheUser_Stor] FOREIGN KEY([CodeStor])
REFERENCES [dbo].[Stor] ([CodeStor])
GO
ALTER TABLE [dbo].[FavoriteStoresForTheUser] CHECK CONSTRAINT [FK_FavoriteParkingForTheUser_Stor]
GO
ALTER TABLE [dbo].[FavoriteStoresForTheUser]  WITH CHECK ADD  CONSTRAINT [FK_FavoriteParkingForTheUser_Users] FOREIGN KEY([UserCode])
REFERENCES [dbo].[Users] ([UserCode])
GO
ALTER TABLE [dbo].[FavoriteStoresForTheUser] CHECK CONSTRAINT [FK_FavoriteParkingForTheUser_Users]
GO
ALTER TABLE [dbo].[Stor]  WITH CHECK ADD  CONSTRAINT [FK_Stor_Locations] FOREIGN KEY([PlaceCode])
REFERENCES [dbo].[Locations] ([LocationCode])
GO
ALTER TABLE [dbo].[Stor] CHECK CONSTRAINT [FK_Stor_Locations]
GO
USE [master]
GO
ALTER DATABASE [wayzeShoop] SET  READ_WRITE 
GO
