//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryForStor
    {
        public long CodeStor { get; set; }
        public long categoryCode { get; set; }
        public string categoryName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Stor Stor { get; set; }
    }
}
