//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stor()
        {
            this.CategoryForStor = new HashSet<CategoryForStor>();
            this.FavoriteParkingForTheUser = new HashSet<FavoriteParkingForTheUser>();
            this.OpeningHoursForDorkingDay = new HashSet<OpeningHoursForDorkingDay>();
            this.OpeningHoursForDorkingDay1 = new HashSet<OpeningHoursForDorkingDay>();
        }
    
        public long CodeStor { get; set; }
        public Nullable<long> PlaceCode { get; set; }
        public string NameStor { get; set; }
        public Nullable<System.TimeSpan> OpeningHours { get; set; }
        public Nullable<System.TimeSpan> ClosingHours { get; set; }
        public Nullable<bool> Sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryForStor> CategoryForStor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteParkingForTheUser> FavoriteParkingForTheUser { get; set; }
        public virtual Locations Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpeningHoursForDorkingDay> OpeningHoursForDorkingDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpeningHoursForDorkingDay> OpeningHoursForDorkingDay1 { get; set; }
    }
}
