//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stor()
        {
            this.CategoryForStors = new HashSet<CategoryForStor>();
            this.FavoriteParkingForTheUsers = new HashSet<FavoriteParkingForTheUser>();
            this.OpeningHoursForDorkingDays = new HashSet<OpeningHoursForDorkingDay>();
            this.OpeningHoursForDorkingDays1 = new HashSet<OpeningHoursForDorkingDay>();
        }
    
        public long CodeStor { get; set; }
        public Nullable<long> PlaceCode { get; set; }
        public string NameStor { get; set; }
        public Nullable<System.TimeSpan> OpeningHours { get; set; }
        public Nullable<System.TimeSpan> ClosingHours { get; set; }
        public Nullable<bool> Sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryForStor> CategoryForStors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteParkingForTheUser> FavoriteParkingForTheUsers { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpeningHoursForDorkingDay> OpeningHoursForDorkingDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpeningHoursForDorkingDay> OpeningHoursForDorkingDays1 { get; set; }
    }
}
