//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wayzeShoopEntities : DbContext
    {
        public wayzeShoopEntities()
            : base("name=wayzeShoopEntities")
        {
        }
        public DbSet<T> GetDbSet<T>() where T : class
        {
            return this.Set<T>();
        }




        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryForStor> CategoryForStors { get; set; }
        public virtual DbSet<FavoriteStoresForTheUser> FavoriteStoresForTheUsers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<OpeningHour> OpeningHours { get; set; }
        public virtual DbSet<OpeningHoursForDorkingDay> OpeningHoursForDorkingDays { get; set; }
        public virtual DbSet<Stor> Stors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkingDaysWeek> WorkingDaysWeeks { get; set; }
    }
}
