//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wayzeShoopEntities1 : DbContext
    {
        public wayzeShoopEntities1()
            : base("name=wayzeShoopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        
            public DbSet<T> GetDbSet<T>() where T : class
            {
                return this.Set<T>();
            }

        

        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryForStor> CategoryForStor { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Stor> Stor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<FavoriteStoresForTheUser> FavoriteStoresForTheUser { get; set; }
    }
}
