//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteToRemamber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<bool> complte { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual user user { get; set; }
    }
}
